### ISSUE TITLE
速度慢

### ISSUE THREAD

**Issue by cceessff** [liuzl/gocc#5]
大神，为什么我转一个文件要6-7秒钟，是我用的有问题还是本来就这样啊

**Comment by liuzl** [comment]
后来没有问题了吗？

**Comment by cceessff** [comment]
换了别的库，问题出在对所有文字进行循环那块，字数一多，就需要循环很多次，所以时间很长

Zhanliang Liu <notifications@github.com> 于2019年2月12日周二 上午10:17写道：
