### ISSUE TITLE
open /usr/local/share/gocc/config/t2s.json: no such file or directory

### ISSUE THREAD

**Issue by twolao** [liuzl/gocc#8]
按照示例代码编译运行提示这个错误
open /usr/local/share/gocc/config/t2s.json: no such file or directory

环境mac os，go version go1.12.4 darwin/amd64
看了config目录下是有这些文件的

**Comment by liuzl** [comment]
是通过如下方式编译的吗？
```sh
git clone https://github.com/liuzl/gocc
cd gocc/cmd
make install
gocc --help
echo "我们是工农子弟兵" | gocc
#我們是工農子弟兵
```

**Comment by twolao** [comment]
thanx，忽略了必须要make install，直接在package import出的问题，make install后就OK了
