### ISSUE TITLE
使用 module管理的项目导入时，编译会报错

### ISSUE THREAD

**Issue by Schr0dingerCat** [liuzl/gocc#9]
谢谢大大的分享
 open /mygo/src/github.com/liuzl/gocc/config/tw2s.json: no such file
是不是打开文件的方式，没有适配module管理模式
还有个问题，我自己的项目，使用了你的这个项目，我项目编译出的程序，需要把你项目里的config dictionary 目录复制到我编译出的可执行文件目录下吗？？

**Comment by AYEE0525** [comment]
我是路人甲，我看了一下原始碼，作者有設計使用引入參數方式設定config路徑:
![image](https://user-images.githubusercontent.com/7544569/85257335-4393a680-b498-11ea-9e31-5a1de12ad9d8.png)

所以只要在你的執行檔後面打上 -dir [Path]即可:
![Screenshot_45](https://user-images.githubusercontent.com/7544569/85257601-af760f00-b498-11ea-8597-feab0027520b.png)
